### PR TITLE
fix: allow transform stream to be null before it's flowing

### PR DESCRIPTION
**Pull request by watson**

### CODE REVIEW

**Review by Qard — APPROVED** [review]

**Comment by Qard** [comment]
6.x seems to be failing. 🤔

**Comment by watson** [comment]
Dang. It's streams that doesn't have a `.destroy()` function in Node.js 6. Since we now allow the use of a gzip stream in stead of a PassThrough stream, we can't make use of `readable-stream`, so we'll have to deal with weird stream stuff from older Node versions :(((

**Comment by watson** [comment]
@Qard fixed it - and found a node core memory leak in the process (technically @mafintosh spotted it, but hey, who's counting)

**Comment by watson** [comment]
I'm not entirely sure how codecov works, but in Node.js 6 the line that it says isn't covered should be covered. But as Travis runs codecov on both Node 6, 8 and 10, I'm not sure if the result we're seeing on codecov is simply just one of those CI-builds or if it's the sum of them all?

**Comment by Qard** [comment]
I'm pretty sure it only includes one of them. It's a common problem with cross-version code coverage testing.

**Review by Qard — APPROVED** [review]

**Pull request merged**
